### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by ktbarrett** [ktbarrett/hello#1]
- [x] README
- [ ] DOCUMENT!!!
- [x] Catch2 tests for C++
- [x] ~~CTest?~~
- [x] Travis
  - [x] C++ tests
    - [x] cmake build test
    - [x] cmake install test
    - [x] pip install C++ test
  - [x] Python tests
- [x] ~~C++ hello library user example~~ Achieved by cmake install test
- [x] split up into several commits showing evolution of project (might be useful for newbies (implying I'm not one))
- [x] doxygen documentation
- [x] sphinx+breathe documentation

**Comment by ktbarrett** [comment]
May need to clean up. the documentation build process leaves garbage in the source directory. I'm not sure if this is a problem, or if there is a solution.
